---
name: "send_configuration_command"
runner_type: "run-python"
description: "sends a configuration command to the device in configuration mode"
enabled: true
entry_point: "send_configuration_command.py"
parameters:
  device:
    type: "string"
    description: "ip or hostname of the switch"
    required: true
  command:
    type: "string"
    description: "configuration command"
    required: true
  username:
    type: "string"
    description: "override configured username"
    required: false
  password:
    type: "string"
    description: "override configured password"
    required: false
  enable_username:
    type: "string"
    description: "override configured enable username"
    required: false
  enable_password:
    type: "string"
    description: "override configured enable password"
    required: false
  via:
    type: "string"
    description: "what way?"
    enum:
      - "telnet"
      - "ssh"
    default: "telnet"
  
